import etw
import psutil
from datetime import datetime
import os

def getProcess(pid):
    process_name = ""
    process_name_cmdline = ""
    for proc in psutil.process_iter():
        if proc.pid == pid:
            process_name = proc.name()
            process_name_cmdline = " ".join(proc.cmdline())
    return process_name, process_name_cmdline

def raw(x):
    data = x[1]
    pid = int(data['EventHeader']['ProcessId'])

    # We don't care for events generated by this process (For now)
    if pid != os.getpid():
        time = int(data['EventHeader']["TimeStamp"])
        time = datetime.utcfromtimestamp(time / (10*1000*1000)-11644473600).strftime('%Y-%m-%d %H:%M:%S')

        eid = int(data['EventHeader']['EventDescriptor']['Id'])
        tid = int(data['EventHeader']['ThreadId'])
        
        task = data['Task Name']

        org_process_name, org_process_name_cmdline = getProcess(pid)
    
        if eid == 11:
            #NameDelete
            FileKey = data["FileKey"]
            FileName = data["FileName"]

            print(f"TimeStamp: {time}\nTask: {task}\nEID: {eid}\nProcessId: {pid}\nProcessName: {org_process_name}\nProcess Commandline: {org_process_name_cmdline}\nThreadId: {tid}\nEvent Description:")
            
            print(f"\tFileKey: {FileKey}")
            print(f"\tFileName: {FileName}\n\n")
  
        elif eid == 30:
            # Create New File
            Irp = data["Irp"]
            ThreadId = data["IssuingThreadId"]
            FileObject = data["FileObject"]
            CreateOptions = data["CreateOptions"]
            CreateAttributes = data["CreateAttributes"]
            ShareAccess = data["ShareAccess"]
            FileName = data["FileName"]

            print(f"TimeStamp: {time}\nTask: {task}\nEID: {eid}\nProcessId: {pid}\nProcessName: {org_process_name}\nProcess Commandline: {org_process_name_cmdline}\nThreadId: {tid}\nEvent Description:")
            
            print(f"\tIrp: {Irp}")
            print(f"\tThreadId: {ThreadId}")
            print(f"\tFileObject: {FileObject}")
            print(f"\tCreateOptions: {CreateOptions}")
            print(f"\tCreateAttributes: {CreateAttributes}")
            print(f"\tShareAccess: {ShareAccess}")
            print(f"\tFileName: {FileName}\n\n")
        

def main():
    #"{EDD08927-9CC4-4E65-B970-C2560FB5C289}" "Microsoft-Windows-Kernel-File"
    name = "Microsoft-Windows-Kernel-File"
    guid = "{EDD08927-9CC4-4E65-B970-C2560FB5C289}"
    providers = [etw.ProviderInfo(name, etw.GUID(guid))]
        #
    with etw.ETW(providers=providers, event_callback=lambda x: raw(x), event_id_filters=[10,11,30]):
        etw.run('etw')

if __name__ == '__main__':
    main()